services:
    # start Mongo service
    mongo:
        image: mongo:7.0.5
        container_name: mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: myroot
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: product-service
        volumes:
            - ./docker/mongodb/data:/data/db
