# Define custom port number
server:
    port: 8180
spring:
    jpa:
        generate-ddl: true
    # Add some datastax database connection
    # Use vault to store and retrieve secrets
    # Define spring Mongo URI
    data:
        mongodb:
            uri: mongodb://myroot:password@localhost:27017/portal-service?authSource=admin
# Signing key
token:
    signing:
        key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351